"use client";
import {useEffect,useState} from "react";
import {Check,Sparkles,Users,Share2} from "lucide-react";
export default function Onboarding(){
 const [step,setStep]=useState(1),[profile,setProfile]=useState({full_name:"",company:"",activity:"",audience:"",tone:"Naturel"}),[social,setSocial]=useState([]),[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/onboarding").then(r=>{if(r.status===401){location.href="/login";return null}return r.json()}).then(j=>{if(!j)return;if(j.profile?.onboarding_completed){location.href="/";return}if(j.profile){setProfile(x=>({...x,...j.profile}));setStep(j.profile.onboarding_step||1)}setSocial(j.social||[])})},[]);
 async function saveProfile(){if(!profile.company&&!profile.activity){setMsg("Indique au moins ton activité ou ta société.");return}const r=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({step:2,profile})});if(r.ok){setStep(2);setMsg("")}}
 async function nextCreation(){await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({step:3})});setStep(3)}
 async function finish(){await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed:true,step:3})});location.href="/ai-media"}
 return <div className="calendarpage"><header><div><p className="eyebrow">BIENVENUE SUR NETWORKLY</p><h1>Prêt en 3 étapes</h1><p>Configure ton activité une seule fois, puis Networkly pourra créer et programmer avec ton contexte.</p></div></header><div className="onboardingsteps">{[["1","Ton activité"],["2","Tes réseaux"],["3","Première création"]].map(([n,t])=><div className={step>=Number(n)?"active":""} key={n}><span>{step>Number(n)?<Check size={16}/>:n}</span><strong>{t}</strong></div>)}</div>
 {step===1&&<div className="admincard"><Users/><h2>Parle-nous de ton activité</h2><div className="fields"><label>Prénom<input value={profile.full_name||""} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>Société / réseau<input value={profile.company||""} onChange={e=>setProfile({...profile,company:e.target.value})}/></label><label>Activité<input value={profile.activity||""} onChange={e=>setProfile({...profile,activity:e.target.value})} placeholder="Beauté, bien-être, bijoux..."/></label></div><label>À qui t’adresses-tu ?<textarea value={profile.audience||""} onChange={e=>setProfile({...profile,audience:e.target.value})}/></label><label>Ton<select value={profile.tone||"Naturel"} onChange={e=>setProfile({...profile,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label><button className="generate" onClick={saveProfile}>Continuer</button>{msg&&<p className="notice">{msg}</p>}</div>}
 {step===2&&<div className="admincard"><Share2/><h2>Connecte tes réseaux</h2><p>{social.length?social.map(x=>x.provider).join(", ")+" connecté(s) ✓":"Tu peux connecter Instagram, Facebook et TikTok maintenant."}</p><a className="generate" href="/social">Connecter mes réseaux</a><button className="linkbtn" onClick={nextCreation}>{social.length?"Continuer":"Je le ferai plus tard"}</button></div>}
 {step===3&&<div className="admincard"><Sparkles/><h2>Crée ta première publication</h2><p>Ton profil est prêt. Networkly peut maintenant préparer ton concept, ta légende et ton visuel.</p><button className="generate" onClick={finish}>Créer ma première publication</button></div>}</div>
}