"use client";
import {useEffect,useState} from "react";
import {Check,Sparkles,Users,Share2,ArrowRight} from "lucide-react";
export default function Onboarding(){
 const [saving,setSaving]=useState(false),[step,setStep]=useState(1),[profile,setProfile]=useState({full_name:"",company:"",activity:"",audience:"",tone:"Naturel"}),[social,setSocial]=useState([]),[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/onboarding").then(r=>{if(r.status===401){location.href="/login";return null}return r.json()}).then(j=>{if(!j)return;if(j.profile?.onboarding_completed){location.href="/";return}if(j.profile){setProfile(x=>({...x,...j.profile}));setStep(j.profile.onboarding_step||1)}setSocial(j.social||[])})},[]);
 async function saveProfile(){if(!profile.company&&!profile.activity){setMsg("Indique au moins ton activité ou ta société.");return}setSaving(true);setMsg("");try{const r=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({step:2,profile})});if(!r.ok)throw Error("Impossible d’enregistrer ton profil.");setStep(2)}catch(e){setMsg(e.message||"Erreur de connexion.")}finally{setSaving(false)}}
 async function nextCreation(){setSaving(true);setMsg("");try{const r=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({step:3})});if(!r.ok)throw Error("Impossible de passer à l’étape suivante.");setStep(3)}catch(e){setMsg(e.message||"Erreur de connexion.")}finally{setSaving(false)}}
 async function finish(){setSaving(true);setMsg("");try{const r=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed:true,step:3})});if(!r.ok)throw Error("Impossible de finaliser la configuration.");location.href="/ai-media"}catch(e){setMsg(e.message||"Erreur de connexion.");setSaving(false)}}
 return <div className="onboardingpage"><div className="onboardingtop"><div className="brand dark"><span>T</span> TESAMI</div><p className="eyebrow">BIENVENUE</p><h1>Configurons ton espace</h1><p>Quelques informations suffisent pour personnaliser tes futures créations.</p></div><div className="onboardingsteps">{[["1","Ton activité"],["2","Tes réseaux"],["3","Première création"]].map(([n,t])=><div className={step>=Number(n)?"active":""} key={n}><span>{step>Number(n)?<Check size={15}/>:n}</span><strong>{t}</strong></div>)}</div>
 {step===1&&<div className="onboardingcard"><div className="cardtitle"><div className="stepicon"><Users size={21}/></div><div><h2>Parle-nous de ton activité</h2><p>TESAMI adaptera les contenus à ton univers.</p></div></div><div className="fields"><label>Prénom<input value={profile.full_name||""} onChange={e=>setProfile({...profile,full_name:e.target.value})} placeholder="Ton prénom"/></label><label>Société / marque<input value={profile.company||""} onChange={e=>setProfile({...profile,company:e.target.value})} placeholder="Nom de ta marque"/></label><label>Activité<input value={profile.activity||""} onChange={e=>setProfile({...profile,activity:e.target.value})} placeholder="Beauté, restauration, immobilier..."/></label></div><div className="onboardingwide"><label>À qui t’adresses-tu ?<textarea value={profile.audience||""} onChange={e=>setProfile({...profile,audience:e.target.value})} placeholder="Décris rapidement ta clientèle idéale..."/></label><label>Style de communication<select value={profile.tone||"Naturel"} onChange={e=>setProfile({...profile,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label></div><div className="onboardingfooter">{msg&&<p className="notice">{msg}</p>}<button className="generate" disabled={saving} onClick={saveProfile}>{saving?"Enregistrement...":"Continuer"} <ArrowRight size={17}/></button></div></div>}
 {step===2&&<div className="onboardingcard compactcard">{msg&&<p className="notice">{msg}</p>}<div className="stepicon"><Share2 size={22}/></div><h2>Connecte tes réseaux</h2><p>{social.length?social.map(x=>x.provider).join(", ")+" connecté(s) ✓":"Relie Instagram, Facebook et TikTok pour publier directement depuis TESAMI."}</p><a className="generate" href="/social">Connecter mes réseaux <ArrowRight size={17}/></a><button className="linkbtn" disabled={saving} onClick={nextCreation}>{social.length?"Continuer":"Je le ferai plus tard"}</button></div>}
 {step===3&&<div className="onboardingcard compactcard">{msg&&<p className="notice">{msg}</p>}<div className="stepicon"><Sparkles size={22}/></div><h2>Tout est prêt</h2><p>TESAMI connaît maintenant ton univers. Crée ta première publication et programme-la en quelques clics.</p><button className="generate" disabled={saving} onClick={finish}>{saving?"Préparation...":"Créer ma première publication"} <ArrowRight size={17}/></button></div>}</div>
}