import {createServerSupabase} from "../../../../lib/supabase/server";
import {createAdminSupabase} from "../../../../lib/supabase/admin";
export async function GET(){
 const s=await createServerSupabase();const {data:{user}}=await s.auth.getUser();if(!user)return Response.json({error:"Connexion requise"},{status:401});
 const {data:p}=await s.from("profiles").select("is_admin").eq("id",user.id).single();if(!p?.is_admin)return Response.json({error:"Accès administrateur requis"},{status:403});
 const a=createAdminSupabase();const checks=[];
 async function table(name){const {error}=await a.from(name).select("*",{head:true,count:"exact"}).limit(1);checks.push({name:"Table "+name,ok:!error,detail:error?.message||"OK"})}
 async function columns(name,cols){const {error}=await a.from(name).select(cols).limit(1);checks.push({name:name+" · "+cols,ok:!error,detail:error?.message||"OK"})}
 await table("networkly_migrations");await table("profiles");await columns("profiles","account_status,is_admin,onboarding_completed,onboarding_step,payment_failed_at,grace_period_ends_at");
 await table("content_items");await columns("content_items","scheduled_at,schedule_timezone,target_networks,publish_mode,is_ai_generated");
 await table("publish_targets");await table("social_connections");await table("media_library");await table("ai_media_jobs");await table("billing_events");await table("admin_customer_notes");await table("admin_audit_log");
 let migrations=[];const {data:m,error:me}=await a.from("networkly_migrations").select("id,description,applied_at").order("applied_at");if(!me)migrations=m||[];const expected=["onboarding","admin_customer_management","payment_grace_period","scheduled_at","suspended_account_rls"];const applied=new Set(migrations.map(x=>x.id));const missingMigrations=expected.filter(x=>!applied.has(x));const env=[["App URL",!!process.env.NEXT_PUBLIC_APP_URL],["Supabase URL",!!process.env.NEXT_PUBLIC_SUPABASE_URL],["Supabase anon key",!!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY],["Supabase service role",!!process.env.SUPABASE_SERVICE_ROLE_KEY],["OpenAI",!!process.env.OPENAI_API_KEY],["Alexya",!!process.env.ALEXYA_API_KEY],["Klaviyo",!!process.env.KLAVIYO_PRIVATE_API_KEY],["Mollie",!!process.env.MOLLIE_API_KEY],["PayPal",!!process.env.PAYPAL_CLIENT_ID&&!!process.env.PAYPAL_CLIENT_SECRET],["Cron secret",!!process.env.CRON_SECRET],["OAuth encryption",!!process.env.SOCIAL_TOKEN_ENCRYPTION_KEY&&!!process.env.OAUTH_STATE_SECRET],["Meta OAuth",!!process.env.META_APP_ID&&!!process.env.META_APP_SECRET],["TikTok OAuth",!!process.env.TIKTOK_CLIENT_KEY&&!!process.env.TIKTOK_CLIENT_SECRET]] .map(([name,ok])=>({name,ok}));return Response.json({ok:checks.every(x=>x.ok)&&missingMigrations.length===0&&env.every(x=>x.ok),checks,migrations,missingMigrations,env});
}