import {createServerSupabase} from "../../../../lib/supabase/server";
import {requireActiveUser} from "../../../../lib/auth/active-user";
export async function POST(req){
 try{
  const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});const user=access.user;
  const form=await req.formData();const {data:settings}=await s.from("user_publish_settings").select("*").eq("user_id",user.id).maybeSingle();const publishNow=form.get("publishNow")==="true";const publishMode=publishNow?"automatic":String(form.get("publishMode")||settings?.publish_mode||"approval");const file=form.get("file");if(!file||typeof file==="string")return Response.json({error:"Fichier requis"},{status:400});
  const allowed=["image/jpeg","image/png","image/webp","video/mp4","video/quicktime","video/webm"];if(!allowed.includes(file.type))return Response.json({error:"Format non accepté"},{status:415});
  const max=file.type.startsWith("video/")?1024*1024*1024:25*1024*1024;if(file.size>max)return Response.json({error:file.type.startsWith("video/")?"Vidéo limitée à 1 Go":"Image limitée à 25 Mo"},{status:413});
  const ext=(file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"");const path=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;
  const {error:up}=await s.storage.from("content-media").upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;
  const networks=[...new Set(String(form.get("networks")||"").split(",").filter(x=>["instagram","facebook","tiktok"].includes(x)))];if(!networks.length)return Response.json({error:"Choisis au moins un réseau."},{status:400});if(networks.includes("tiktok")&&!file.type.startsWith("video/"))return Response.json({error:"TikTok accepte actuellement uniquement les vidéos dans Networkly."},{status:409});if(publishMode!=="draft"){const {data:connections}=await s.from("social_connections").select("provider").eq("user_id",user.id).eq("connected",true).in("provider",networks);const connected=new Set((connections||[]).map(x=>x.provider));const missing=networks.filter(x=>!connected.has(x));if(missing.length)return Response.json({error:`Connecte d’abord : ${missing.join(", ")}`},{status:409})}const scheduledAt=String(form.get("scheduledAt")||"").trim()||null;const timezone=String(form.get("timezone")||"Europe/Paris");
  const {data,error}=await s.from("content_items").insert({user_id:user.id,scheduled_date:publishNow?new Date().toISOString().slice(0,10):form.get("date"),scheduled_time:publishNow?new Date().toTimeString().slice(0,5):(form.get("time")||null),scheduled_at:publishNow?new Date().toISOString():scheduledAt,schedule_timezone:timezone,content_type:file.type.startsWith("video/")?"Vidéo":"Publication",platform:networks.join(", "),target_networks:networks,objective:"Contenu personnel",title:file.name,body:String(form.get("caption")||""),status:"planned",publish_mode:publishMode,media_path:path,media_type:file.type,is_ai_generated:false,subtitles_enabled:form.get("subtitles")==="true",subtitle_style:String(form.get("subtitleStyle")||"dynamic")}).select().single();
  if(error){await s.storage.from("content-media").remove([path]);throw error}
  if(form.get("saveToLibrary")==="true")await s.from("media_library").insert({user_id:user.id,source:"imported",media_path:path,media_type:file.type,original_name:file.name,title:file.name,size_bytes:file.size});
  if(publishMode!=="draft")await s.from("publish_targets").insert(networks.map(provider=>({user_id:user.id,content_id:data.id,provider,status:publishNow||publishMode==="automatic"?"pending":"pending_approval"})));if(publishNow){const base=new URL(req.url).origin;const rr=await fetch(base+"/api/publish/run",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+(process.env.CRON_SECRET||"")},body:JSON.stringify({contentId:data.id})});const out=await rr.json().catch(()=>({}));if(!rr.ok)return Response.json({item:data,error:out.error||"Le fichier est prêt mais la publication immédiate a échoué."},{status:502});return Response.json({item:data,published:true,result:out})}return Response.json({item:data});
 }catch{return Response.json({error:"Impossible d’enregistrer la publication."},{status:500})}
}