import {createServerSupabase} from "../../../lib/supabase/server";
import {requireActiveUser} from "../../../lib/auth/active-user";
export async function POST(request){
 try{
  const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});
  const data=await request.json();const p=data.profile||{};const goal=String(data.goal||"").trim();if(goal.length<3)return Response.json({error:"Décris ton objectif."},{status:400});
  if(!process.env.OPENAI_API_KEY)return Response.json({concept:"Mode démo : concept de publication premium autour de ton objectif.",caption:"Mode démo : configure OPENAI_API_KEY pour générer la légende complète.",visualPrompt:"Visuel social media premium, moderne, vertical, sans texte intégré",suggestedNetworks:["instagram"],suggestedDayOffset:1,suggestedHour:"18:00"});
  const instruction=`Tu es Networkly AI. Prépare UNE publication complète de marketing de réseau, sans promesse de revenus ou résultat garanti. Objectif: ${goal}. Réseau: ${data.network||"Instagram"}. Ton: ${data.tone||"Naturel"}. Société/activité: ${p.company||""} ${p.activity||""}. Cible: ${p.audience||""}. Retourne UNIQUEMENT un objet JSON valide, sans markdown, sans bloc de code et sans texte avant ou après. concept, caption et visualPrompt sont des chaînes. hashtags est un tableau de 5 à 8 hashtags pertinents, avec #, adaptés au réseau choisi. suggestedNetworks est un tableau contenant uniquement instagram, tiktok et/ou youtube selon les réseaux les plus adaptés. suggestedDayOffset est un entier de 0 à 7. suggestedHour est une heure locale HH:MM. caption doit être directement publiable avec CTA pertinent. visualPrompt doit décrire uniquement le visuel à générer, sans logo ni texte incrusté.`;
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:"gpt-5-mini",input:instruction})});
  const j=await r.json();if(!r.ok){const detail=j?.error?.message||j?.error?.code||j?.message||"Erreur du service IA";console.error("OpenAI generate-complete:",r.status,detail);return Response.json({error:"OpenAI : "+detail},{status:502})}const raw=j.output_text||j?.output?.find(x=>x.type==="message")?.content?.find(x=>x.type==="output_text")?.text||"";if(!raw)throw new Error("La réponse IA est vide.");let parsed;try{parsed=JSON.parse(raw)}catch{const match=raw.match(/\{[\s\S]*\}/);if(!match)throw new Error("TESAMI a reçu une réponse IA invalide. Réessaie.");parsed=JSON.parse(match[0])}return Response.json(parsed);
 }catch(e){return Response.json({error:e.message||"Création impossible"},{status:500})}
}
