import {createServerSupabase} from "../../../lib/supabase/server";
import {requireActiveUser} from "../../../lib/auth/active-user";
export async function POST(request){
 try{
  const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});
  const data=await request.json();const p=data.profile||{};const goal=String(data.goal||"").trim();if(goal.length<3)return Response.json({error:"Décris ton objectif."},{status:400});
  if(!process.env.OPENAI_API_KEY)return Response.json({concept:"Mode démo : concept de publication premium autour de ton objectif.",caption:"Mode démo : configure OPENAI_API_KEY pour générer la légende complète.",visualPrompt:"Visuel social media premium, moderne, vertical, sans texte intégré",suggestedNetworks:["instagram"],suggestedDayOffset:1,suggestedHour:"18:00"});
  const instruction=`Tu es Networkly AI. Prépare UNE publication complète de marketing de réseau, sans promesse de revenus ou résultat garanti. Objectif: ${goal}. Réseau: ${data.network||"Instagram"}. Ton: ${data.tone||"Naturel"}. Société/activité: ${p.company||""} ${p.activity||""}. Cible: ${p.audience||""}. Retourne uniquement un JSON valide. concept, caption et visualPrompt sont des chaînes. suggestedNetworks est un tableau contenant uniquement instagram, facebook et/ou tiktok selon les réseaux les plus adaptés. suggestedDayOffset est un entier de 0 à 7. suggestedHour est une heure locale HH:MM. caption doit être directement publiable avec CTA pertinent. visualPrompt doit décrire uniquement le visuel à générer, sans logo ni texte incrusté.`;
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:instruction,text:{format:{type:"json_schema",name:"networkly_complete_post",strict:true,schema:{type:"object",properties:{concept:{type:"string"},caption:{type:"string"},visualPrompt:{type:"string"},suggestedNetworks:{type:"array",items:{type:"string",enum:["instagram","facebook","tiktok"]}},suggestedDayOffset:{type:"integer",minimum:0,maximum:7},suggestedHour:{type:"string",pattern:"^(?:[01]\\d|2[0-3]):[0-5]\\d$"}},required:["concept","caption","visualPrompt","suggestedNetworks","suggestedDayOffset","suggestedHour"],additionalProperties:false}}}})});
  const j=await r.json();if(!r.ok)throw new Error("Erreur du service IA");return Response.json(JSON.parse(j.output_text));
 }catch(e){return Response.json({error:e.message||"Création impossible"},{status:500})}
}
