"use client";
import {useEffect,useState} from "react";
import {createClient} from "../lib/supabase/client";
import {Sparkles,Video,MessageCircle,Users,CalendarDays,Instagram,UserRound,Save,LayoutDashboard,Image as ImageIcon,Share2,CreditCard,Plus,Clock3,Copy,Check,LogOut} from "lucide-react";
const tools=[["Publication",Sparkles,"Post Instagram ou Facebook"],["Reel / TikTok",Video,"Hook + script vidéo"],["Stories",Instagram,"Séquence de stories"],["Message",MessageCircle,"Message naturel"],["Communauté",Users,"Développer ton audience"],["Ma semaine",CalendarDays,"7 jours de contenu"]];
const presets={
 "Publication":{goal:"Vendre un produit",network:"Instagram",placeholder:"Ex : présenter un produit, annoncer une nouveauté..."},
 "Reel / TikTok":{goal:"Créer de l'engagement",network:"TikTok",placeholder:"Ex : une démonstration produit, un conseil rapide, une transformation..."},
 "Stories":{goal:"Créer de l'engagement",network:"Instagram",placeholder:"Ex : créer une séquence de 4 stories pour présenter une offre..."},
 "Message":{goal:"Créer de l'engagement",network:"Instagram",placeholder:"Ex : répondre à un prospect, relancer un client, annoncer une nouveauté..."},
 "Communauté":{goal:"Développer mon audience",network:"Instagram",placeholder:"Ex : lancer une discussion, poser une question, créer un rendez-vous communautaire..."},
 "Ma semaine":{goal:"Développer mon audience",network:"Instagram",placeholder:"Ex : préparer 7 jours autour d’un lancement, d’un produit ou d’un thème..."}
};
const empty={name:"",company:"",activity:"",audience:"",tone:"Naturel",shopUrl:"",joinUrl:""};
export default function Home(){
 const [accountPlan,setAccountPlan]=useState(null),[logoutOpen,setLogoutOpen]=useState(false),[loggingOut,setLoggingOut]=useState(false),[logoutError,setLogoutError]=useState(""),[tab,setTab]=useState("studio"),[selected,setSelected]=useState("Publication"),[result,setResult]=useState(""),[hashtags,setHashtags]=useState([]),[copied,setCopied]=useState(false),[loading,setLoading]=useState(false),[profile,setProfile]=useState(empty),[form,setForm]=useState({goal:"Vendre un produit",network:"Instagram",tone:"Naturel",subject:""});
 useEffect(()=>{fetch("/api/account-status").then(r=>{if(r.status===401){location.href="/login";return null}return r.json()}).then(a=>{if(!a)return;setAccountPlan(a.plan||"free");if(a?.status==="suspended"&&!a?.isAdmin){location.href="/suspended";return}fetch("/api/onboarding").then(r=>r.json()).then(j=>{if(!j)return;if(!j.profile?.onboarding_completed){location.href="/onboarding";return}const p=j.profile||{};setProfile({name:p.full_name||"",company:p.company||"",activity:p.activity||"",audience:p.audience||"",tone:p.tone||"Naturel",shopUrl:p.shop_url||"",joinUrl:p.join_url||""})})}).catch(()=>{});},[]);
 const logout=async()=>{setLoggingOut(true);setLogoutError("");try{const {error}=await createClient().auth.signOut();if(error)throw error;window.location.replace("/login")}catch{setLogoutError("La déconnexion a échoué. Réessaie.");setLoggingOut(false)}};
 const chooseTool=(name)=>{const p=presets[name]||presets.Publication;setSelected(name);setResult("");setHashtags([]);setForm(v=>({...v,goal:p.goal,network:p.network}));setTimeout(()=>document.getElementById("tesami-composer")?.scrollIntoView({behavior:"smooth",block:"start"}),50)};
 const save=async()=>{const r=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:{full_name:profile.name,company:profile.company,activity:profile.activity,audience:profile.audience,tone:profile.tone,shop_url:profile.shopUrl,join_url:profile.joinUrl}})});if(r.ok){localStorage.setItem("tesami-profile",JSON.stringify(profile));alert("Profil enregistré")}else alert("Impossible d’enregistrer le profil")};
 const generate=async()=>{if(["Publication","Stories","Reel / TikTok"].includes(selected)){const q=new URLSearchParams({mode:selected==="Stories"?"stories":selected==="Reel / TikTok"?"video":"post",goal:form.goal,network:form.network,tone:form.tone,subject:form.subject});location.href="/ai-media?"+q.toString();return}setLoading(true);setResult("");setHashtags([]);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:selected,...form,profile})});const d=await r.json();const raw=d.content||d.error||"Impossible de générer le contenu.";const marker="HASHTAGS_SUGGERES:";const pos=raw.indexOf(marker);if(pos>=0){setResult(raw.slice(0,pos).trim());setHashtags(raw.slice(pos+marker.length).trim().split(/\s+/).filter(x=>x.startsWith("#")))}else setResult(raw)}catch{setResult("Erreur de connexion au générateur.")}finally{setLoading(false)}};
 return <main className="appframe">{logoutOpen&&<div className="tesami-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!loggingOut)setLogoutOpen(false)}}><div className="tesami-logout-dialog" role="dialog" aria-modal="true" aria-labelledby="tesami-logout-title"><div className="tesami-dialog-icon"><LogOut size={24}/></div><h2 id="tesami-logout-title">À bientôt sur TESAMI !</h2><p>Tu souhaites te déconnecter de ton espace ? Tu pourras te reconnecter à tout moment.</p>{logoutError&&<p className="tesami-dialog-error" role="alert">{logoutError}</p>}<div className="tesami-dialog-actions"><button type="button" className="tesami-dialog-cancel" disabled={loggingOut} onClick={()=>setLogoutOpen(false)}>Rester connecté</button><button type="button" className="tesami-dialog-confirm" disabled={loggingOut} onClick={logout}>{loggingOut?"Déconnexion...":"Se déconnecter"}</button></div></div></div>}<aside><div className="brand"><span>T</span> TESAMI</div><nav><b>Créer</b><a className={tab==="studio"?"active":""} onClick={()=>setTab("studio")}><Sparkles size={17}/> Studio</a><a href="/ai-media"><Plus size={17}/> Création IA</a><a href="/schedule"><Clock3 size={17}/> Programmer</a><b>Organiser</b><a href="/calendar"><CalendarDays size={17}/> Calendrier</a><a href="/statistics"><LayoutDashboard size={17}/> Statistiques</a><a href="/library"><ImageIcon size={17}/> Bibliothèque</a><a href="/social"><Share2 size={17}/> Réseaux</a><b>Compte</b><a className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><UserRound size={17}/> Ma marque</a><a href="/billing"><CreditCard size={17}/> Abonnement</a><button type="button" className="tesami-logout" onClick={()=>setLogoutOpen(true)}><LogOut size={17}/> Se déconnecter</button></nav><div className="plan"><small>TON ABONNEMENT</small><strong>{accountPlan===null?"Chargement...":accountPlan==="pro"?"TESAMI PRO":"TESAMI FREE"}</strong><span>Création & programmation</span><a className="tesami-plan-link" href="/billing">Voir mon abonnement →</a><div className="tesami-credits-note"><Sparkles size={16}/><span>Crédits IA : suivi non activé</span></div></div></aside><section className="dashboardcontent"><header className="dashboardheader"><div><p className="eyebrow">{tab==="studio"?"TON ESPACE TESAMI":"IDENTITÉ DE MARQUE"}</p><h1>{tab==="studio"?<>Bonjour{profile.name?", "+profile.name:""}.</>:"Ton identité de marque"}</h1><p>{tab==="studio"?"Crée, programme et pilote ta présence sociale depuis un seul endroit.":"TESAMI utilise ces informations pour personnaliser chaque création."}</p></div><button className="profile" onClick={()=>setTab("profile")}><UserRound size={18}/></button></header>
 {tab==="profile"?<div className="composer profileform"><div className="cardtitle"><div className="stepicon"><UserRound size={20}/></div><div><h2>Ton univers</h2><p>Ces informations guident l’IA sans t’enfermer dans un secteur.</p></div></div><div className="fields"><label>Prénom<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Société / marque<input value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})}/></label><label>Activité / produits<input value={profile.activity} onChange={e=>setProfile({...profile,activity:e.target.value})}/></label></div><label>Audience cible<textarea value={profile.audience} onChange={e=>setProfile({...profile,audience:e.target.value})}/></label><div className="fields"><label>Ton<select value={profile.tone} onChange={e=>setProfile({...profile,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label><label>Lien principal<input value={profile.shopUrl} onChange={e=>setProfile({...profile,shopUrl:e.target.value})}/></label><label>Lien secondaire<input value={profile.joinUrl} onChange={e=>setProfile({...profile,joinUrl:e.target.value})}/></label></div><button className="generate" onClick={save}><Save size={18}/> Enregistrer mon profil</button></div>:<>
 <div className="quickactions"><a href="/ai-media"><span><Sparkles size={20}/></span><div><strong>Créer avec l’IA</strong><small>Concept, texte et visuel</small></div></a><a href="/schedule"><span><Clock3 size={20}/></span><div><strong>Programmer</strong><small>Publier au bon moment</small></div></a><a href="/calendar"><span><CalendarDays size={20}/></span><div><strong>Mon calendrier</strong><small>Voir les prochaines publications</small></div></a><a href="/social"><span><Share2 size={20}/></span><div><strong>Mes réseaux</strong><small>Gérer les connexions</small></div></a></div>
 <div className="tesami-overview"><div className="tesami-welcome"><span className="tesami-sparkle">✦ TESAMI STUDIO</span><h2>Votre créativité, sans limites.</h2><p>Imaginez vos contenus, préparez vos prochaines publications et retrouvez tous vos outils au même endroit.</p><div className="tesami-welcome-actions"><a href="/ai-media">✦ Créer un contenu</a><a href="/calendar">Voir mon calendrier →</a></div></div><div className="tesami-shortcuts"><a href="/ai-media"><span>✦</span><strong>Studio IA</strong><small>Posts, Reels et Stories</small></a><a href="/calendar"><span>▦</span><strong>Calendrier</strong><small>Organiser mes contenus</small></a><a href="/library"><span>▧</span><strong>Bibliothèque</strong><small>Retrouver mes médias</small></a><a href="/statistics"><span>↗</span><strong>Statistiques</strong><small>Suivre mes résultats</small></a></div></div>
 <div className="sectiontitle"><div><p className="eyebrow">CRÉATION RAPIDE</p><h2>Que veux-tu préparer ?</h2></div><LayoutDashboard size={20}/></div><div className="grid">{tools.map(([name,Icon,desc])=><button key={name} className={"card "+(selected===name?"chosen":"")} onClick={()=>chooseTool(name)}><Icon/><h3>{name}</h3><p>{desc}</p></button>)}</div>
 <div className="composer" id="tesami-composer"><p className="eyebrow">ASSISTANT DE CRÉATION</p><h2>{selected}</h2><p>{selected==="Publication"?"Crée un post complet prêt à publier.":selected==="Reel / TikTok"?"Prépare le hook, le script et la légende de ta vidéo.":selected==="Stories"?"Crée une séquence cohérente de stories.":selected==="Message"?"Rédige un message naturel adapté à ton objectif.":selected==="Communauté"?"Crée un contenu pensé pour faire réagir et développer ton audience.":"Prépare un véritable planning de contenu sur 7 jours."}</p><div className="fields"><label>Objectif<select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}><option>Vendre un produit</option><option>Créer de l'engagement</option><option>Développer mon audience</option></select></label><label>Réseau<select value={form.network} onChange={e=>setForm({...form,network:e.target.value})}><option>Instagram</option><option>Facebook</option><option>TikTok</option><option>YouTube</option></select></label><label>Ton<select value={form.tone} onChange={e=>setForm({...form,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label></div><label>Sujet / produit<textarea value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder={presets[selected]?.placeholder||"Décris ce que tu veux créer..."}/></label><button className="generate" disabled={loading} onClick={generate}><Sparkles size={18}/>{loading?" Création...":selected==="Ma semaine"?" Générer mes 7 jours":selected==="Stories"?" Créer mes stories":selected==="Reel / TikTok"?" Créer mon Reel / TikTok":selected==="Publication"?" Créer ma publication":" Générer avec TESAMI"}</button>{result&&<div className="result"><b>Contenu prêt à publier</b><p style={{whiteSpace:"pre-wrap"}}>{result}</p>{hashtags.length>0&&<div className="notice"><b>✨ Hashtags suggérés</b><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:10}}>{hashtags.map(h=><button key={h} type="button" className="linkbtn" onClick={()=>setResult(v=>v.includes(h)?v:(v.trim()+" "+h))}>{h}</button>)}</div><small>Clique sur un hashtag pour l’ajouter au texte.</small></div>}<button className="linkbtn" onClick={async()=>{await navigator.clipboard?.writeText(result);setCopied(true);setTimeout(()=>setCopied(false),1600)}}>{copied?<><Check size={16}/> Copié !</>:<><Copy size={16}/> Copier le texte</>}</button></div>}</div></>}
 </section></main>}