"use client";
import {useEffect,useState} from "react";
import {Sparkles,Video,MessageCircle,Users,CalendarDays,Instagram,UserRound,Save} from "lucide-react";
const tools=[["Publication",Sparkles,"Post Instagram ou Facebook"],["Reel / TikTok",Video,"Hook + script vidéo"],["Stories",Instagram,"Séquence de stories"],["Prospection",MessageCircle,"Message naturel"],["Recrutement",Users,"Attirer de nouveaux partenaires"],["Ma semaine",CalendarDays,"7 jours de contenu"]];
const empty={name:"",company:"",activity:"",audience:"",tone:"Naturel",shopUrl:"",joinUrl:""};
export default function Home(){
 const [tab,setTab]=useState("studio"),[selected,setSelected]=useState("Publication"),[result,setResult]=useState(""),[loading,setLoading]=useState(false),[profile,setProfile]=useState(empty),[form,setForm]=useState({goal:"Vendre un produit",network:"Instagram",tone:"Naturel",subject:""});
 useEffect(()=>{fetch("/api/onboarding").then(r=>{if(r.status===401){location.href="/login";return null}return r.json()}).then(j=>{if(j&&!j.profile?.onboarding_completed)location.href="/onboarding"});try{const p=localStorage.getItem("networkly-profile");if(p)setProfile(JSON.parse(p))}catch{}},[]);
 const save=()=>{localStorage.setItem("networkly-profile",JSON.stringify(profile));alert("Profil enregistré");};
 const generate=async()=>{setLoading(true);setResult("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:selected,...form,profile})});const d=await r.json();setResult(d.content||d.error||"Impossible de générer le contenu.")}catch{setResult("Erreur de connexion au générateur.")}finally{setLoading(false)}};
 return <main><aside><div className="brand"><span>N</span> Networkly AI</div><nav><b>Studio IA</b><a className={tab==="studio"?"active":""} onClick={()=>setTab("studio")}>Créer du contenu</a><b>Mon activité</b><a className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}>Profil MLM</a><a href="/social">Réseaux sociaux</a><a href="/billing">Abonnement</a></nav><div className="plan">PRO<br/><strong>7,90 € / mois</strong><small>Mollie + PayPal</small></div></aside><section><header><div><p className="eyebrow">{tab==="studio"?"STUDIO DE CONTENU":"PERSONNALISATION"}</p><h1>{tab==="studio"?"Que veux-tu créer aujourd’hui ?":"Ton profil MLM"}</h1><p>{tab==="studio"?"Networkly utilise ton profil pour écrire comme toi.":"Renseigne-le une fois : l’IA s’en servira pour tes futurs contenus."}</p></div><button className="profile"><UserRound size={18}/></button></header>
 {tab==="profile"?<div className="composer profileform"><div className="fields"><label>Prénom<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Société MLM<input value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})} placeholder="Ex : Chogan"/></label><label>Activité / produits<input value={profile.activity} onChange={e=>setProfile({...profile,activity:e.target.value})} placeholder="Parfums, beauté..."/></label></div><label>Clientèle cible<textarea value={profile.audience} onChange={e=>setProfile({...profile,audience:e.target.value})} placeholder="Ex : femmes 25-45 ans intéressées par les parfums..."/></label><div className="fields"><label>Ton<select value={profile.tone} onChange={e=>setProfile({...profile,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label><label>Lien boutique<input value={profile.shopUrl} onChange={e=>setProfile({...profile,shopUrl:e.target.value})}/></label><label>Lien inscription<input value={profile.joinUrl} onChange={e=>setProfile({...profile,joinUrl:e.target.value})}/></label></div><button className="generate" onClick={save}><Save size={18}/> Enregistrer mon profil</button></div>:<>
 <div className="grid">{tools.map(([name,Icon,desc])=><button key={name} className={"card "+(selected===name?"chosen":"")} onClick={()=>setSelected(name)}><Icon/><h3>{name}</h3><p>{desc}</p></button>)}</div>
 <div className="composer"><p className="eyebrow">GÉNÉRATEUR</p><h2>{selected}</h2><div className="fields"><label>Objectif<select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}><option>Vendre un produit</option><option>Créer de l'engagement</option><option>Recruter</option></select></label><label>Réseau<select value={form.network} onChange={e=>setForm({...form,network:e.target.value})}><option>Instagram</option><option>Facebook</option><option>TikTok</option></select></label><label>Ton<select value={form.tone} onChange={e=>setForm({...form,tone:e.target.value})}><option>Naturel</option><option>Premium</option><option>Dynamique</option><option>Professionnel</option></select></label></div><label>Sujet / produit<textarea value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Ex : présenter un parfum, annoncer une promotion..."/></label><button className="generate" disabled={loading} onClick={generate}><Sparkles size={18}/>{loading?" Création...":" Générer avec Networkly AI"}</button>{result&&<div className="result"><b>Contenu prêt à publier</b><p>{result}</p><button onClick={()=>navigator.clipboard?.writeText(result)}>Copier</button></div>}</div></>}
 </section></main>}