"use client";
import {useEffect,useRef,useState} from "react";
import {Sparkles,Image as ImageIcon,Video,Library,CalendarClock,Upload,X} from "lucide-react";
export default function AiMedia(){
 const [kind,setKind]=useState("image"),[prompt,setPrompt]=useState(""),[ratio,setRatio]=useState("1:1"),[duration,setDuration]=useState(5),[job,setJob]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[saved,setSaved]=useState(null),[caption,setCaption]=useState(""),[autoGoal,setAutoGoal]=useState(""),[concept,setConcept]=useState(""),[profile,setProfile]=useState({}),[suggestion,setSuggestion]=useState(null),[reference,setReference]=useState(null),[referencePreview,setReferencePreview]=useState(""),[elapsed,setElapsed]=useState(0),[phase,setPhase]=useState("");
 const timer=useRef(null),chrono=useRef(null); useEffect(()=>{const g=sessionStorage.getItem("tesami_ai_goal");if(g){setAutoGoal(g);sessionStorage.removeItem("tesami_ai_goal")}fetch("/api/onboarding").then(r=>r.json()).then(j=>setProfile(j.profile||{})).catch(()=>{});return()=>{clearInterval(timer.current);clearInterval(chrono.current)}},[]);
 async function uploadReference(){if(!reference)return null;if(reference.size>10*1024*1024)throw new Error("La photo doit faire moins de 10 Mo.");const pr=await fetch("/api/alexya/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentType:reference.type,fileName:reference.name,mediaKind:kind})});const pj=await pr.json();if(!pr.ok)throw new Error(pj.error||"Préparation de l’upload impossible");const put=await fetch(pj.uploadUrl,{method:"PUT",headers:{"Content-Type":reference.type},body:reference});if(!put.ok)throw new Error("Envoi de la photo impossible");return pj.publicUrl}
 function startChrono(label){setPhase(label);setElapsed(0);clearInterval(chrono.current);chrono.current=setInterval(()=>setElapsed(v=>v+1),1000)}
 function stopChrono(){clearInterval(chrono.current);chrono.current=null;setPhase("")}
 async function generate(e){e.preventDefault();setBusy(true);startChrono(reference?"Préparation de ta photo":"TESAMI prépare ton visuel");setMsg(reference?"Envoi de la photo de référence...":"Création lancée...");let referenceUrl=null;try{referenceUrl=await uploadReference()}catch(err){setBusy(false);stopChrono();setMsg(err.message);return}if(reference)startChrono("Photo envoyée · génération du visuel");setMsg("Création lancée...");const r=await fetch("/api/alexya/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,prompt,aspectRatio:ratio,duration,referenceUrl})});const j=await r.json();setBusy(false);if(!r.ok){stopChrono();setMsg(j.error||"Erreur");return}setJob(j.job);startChrono("Génération IA en cours");watch(j.job.id)}
 function watch(id){clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch("/api/alexya/status?id="+encodeURIComponent(id));const j=await r.json();if(r.ok){setJob(j.job);if(["completed","failed"].includes(j.job.status)){clearInterval(timer.current);stopChrono();setMsg(j.job.status==="completed"?"Ton média est prêt ✓":"La génération a échoué.")}}},3000)}
 async function save(go=false){setBusy(true);const r=await fetch("/api/alexya/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.id})});const j=await r.json();setBusy(false);if(r.ok){setSaved(j.item);setMsg("Ajouté à ta bibliothèque ✓");if(go)prepareSchedule();location.href="/schedule?media="+encodeURIComponent(j.item.id)}else setMsg(j.error||"Enregistrement impossible")}
 async function completePost(){if(autoGoal.trim().length<3){setMsg("Décris ton objectif.");return}setBusy(true);setMsg("TESAMI prépare ta publication...");const r=await fetch("/api/generate-complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal:autoGoal,network:"Instagram / TikTok",tone:profile.tone||"Naturel",profile})});const j=await r.json();if(!r.ok){setBusy(false);setMsg(j.error||"Création impossible");return}setConcept(j.concept);setCaption(j.caption);setPrompt(j.visualPrompt);setSuggestion({networks:j.suggestedNetworks||["instagram"],dayOffset:Number(j.suggestedDayOffset||0),hour:j.suggestedHour||"18:00"});setKind("image");setRatio("4:5");const gr=await fetch("/api/alexya/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"image",prompt:j.visualPrompt,aspectRatio:"4:5"})});const gj=await gr.json();setBusy(false);if(!gr.ok){setMsg(gj.error||"Le concept est prêt mais le visuel n’a pas pu être lancé.");return}setJob(gj.job);setMsg("Concept et légende prêts. Création du visuel...");watch(gj.job.id)}
 function prepareSchedule(){sessionStorage.setItem("tesami_schedule_caption",caption);if(suggestion){const d=new Date();d.setDate(d.getDate()+suggestion.dayOffset);sessionStorage.setItem("tesami_schedule_networks",JSON.stringify(suggestion.networks));sessionStorage.setItem("tesami_schedule_date",d.toLocaleDateString("en-CA"));sessionStorage.setItem("tesami_schedule_time",suggestion.hour)}}
 async function generateCaption(){setBusy(true);const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request:"Rédige une légende de réseau social prête à publier pour ce visuel : "+prompt,platform:"Instagram / TikTok",tone:"naturel et engageant"})});const j=await r.json();setBusy(false);setCaption(j.text||j.content||j.result||"");}
 return <div className="calendarpage"><header><div><p className="eyebrow">STUDIO VISUEL IA</p><h1>Crée ton visuel</h1><p>Génère une image ou une vidéo, puis conserve-la dans ta bibliothèque.</p></div><a href="/" className="linkbtn">Retour</a></header>
 <div className="admincard" style={{marginBottom:20}}><p className="eyebrow">PUBLICATION COMPLÈTE</p><h2>Donne simplement ton objectif</h2><p>TESAMI prépare le concept, la légende et le visuel.</p><label>Que veux-tu obtenir ?<textarea value={autoGoal} onChange={e=>setAutoGoal(e.target.value)} placeholder="Ex : recruter de nouvelles vendeuses pour mon activité, présenter mon nouveau parfum..."/></label><button className="generate" type="button" disabled={busy} onClick={completePost}><Sparkles size={18}/> Créer toute ma publication</button>{concept&&<div className="result"><b>Concept proposé</b><p>{concept}</p></div>}</div><div className="aistudio"><form className="admincard" onSubmit={generate}><div className="typepicker"><button type="button" className={kind==="image"?"active":""} onClick={()=>{setKind("image");setRatio("1:1")}}><ImageIcon/> Image</button><button type="button" className={kind==="video"?"active":""} onClick={()=>{setKind("video");setRatio("9:16")}}><Video/> Vidéo</button></div>
 <label>Décris ce que tu veux créer<textarea required minLength="3" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex : visuel publicitaire premium, lumière chaude..."/></label>
 <label>Photo de référence <span style={{fontWeight:400,opacity:.7}}>(facultatif)</span><div style={{marginTop:8,border:"1px dashed #cbd5e1",borderRadius:14,padding:14}}>{referencePreview?<div style={{display:"flex",gap:12,alignItems:"center"}}><img src={referencePreview} alt="Référence" style={{width:72,height:72,objectFit:"cover",borderRadius:12}}/><div style={{flex:1}}><b>{reference?.name}</b><p style={{margin:"4px 0 0",fontSize:13}}>TESAMI utilisera cette photo comme référence visuelle.</p></div><button type="button" className="linkbtn" onClick={()=>{setReference(null);URL.revokeObjectURL(referencePreview);setReferencePreview("")}}><X size={16}/> Retirer</button></div>:<label style={{cursor:"pointer",display:"flex",gap:8,alignItems:"center",margin:0}}><Upload size={18}/> Ajouter une photo (JPG, PNG ou WebP, 10 Mo max)<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(referencePreview)URL.revokeObjectURL(referencePreview);setReference(file);setReferencePreview(URL.createObjectURL(file))}}/></label>}</div></label>
 <label>Format<select value={ratio} onChange={e=>setRatio(e.target.value)}>{kind==="image"?<><option value="1:1">Post carré Instagram / Facebook (1:1)</option><option value="4:5">Post Instagram portrait (4:5)</option><option value="9:16">Story Instagram / TikTok / Reel (9:16)</option><option value="16:9">Miniature / paysage (16:9)</option></>:<><option value="9:16">TikTok / Reel / Story (9:16)</option><option value="16:9">YouTube / vidéo paysage (16:9)</option></>}</select></label>
 {kind==="video"&&<label>Durée<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="5">5 secondes</option><option value="10">10 secondes</option></select></label>}
 <button className="generate" disabled={busy}><Sparkles size={18}/> {busy?"Création...":"Générer avec l’IA"}</button>{phase&&<div className="notice" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><span>⏳ {phase}</span><strong>{Math.floor(elapsed/60).toString().padStart(2,"0")}:{(elapsed%60).toString().padStart(2,"0")}</strong></div>}{msg&&<p className="notice">{msg}</p>}</form>
 <div className="admincard airesult"><p className="eyebrow">APERÇU</p>{!job&&<div className="empty">Ton prochain visuel apparaîtra ici.</div>}{job&&job.status!=="completed"&&<div className="generating"><Sparkles/><strong>Génération en cours</strong><span>TESAMI prépare ton média.</span></div>}{job?.status==="completed"&&job.output_url&&<>{job.media_kind==="video"?<video src={job.output_url} controls/>:<img src={job.output_url} alt="Création IA"/>}<label>Légende<textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Ajoute une légende ou génère-la avec TESAMI..."/></label><button className="linkbtn" type="button" onClick={generateCaption} disabled={busy}>Générer la légende</button>{!saved?<><button className="generate" onClick={()=>save(false)} disabled={busy}><Library size={18}/> Ajouter à ma bibliothèque</button><button className="generate" onClick={()=>save(true)} disabled={busy}><CalendarClock size={18}/> Programmer maintenant</button></>:<button className="generate" onClick={()=>{prepareSchedule();location.href="/schedule?media="+encodeURIComponent(saved.id)}}>Programmer ce média</button>}</>}</div></div></div>
}