"use client";
import {useEffect,useRef,useState} from "react";
import {Sparkles,Image as ImageIcon,Video,Library,CalendarClock} from "lucide-react";
export default function AiMedia(){
 const [kind,setKind]=useState("image"),[prompt,setPrompt]=useState(""),[ratio,setRatio]=useState("1:1"),[duration,setDuration]=useState(5),[job,setJob]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[saved,setSaved]=useState(null),[caption,setCaption]=useState(""),[autoGoal,setAutoGoal]=useState(""),[concept,setConcept]=useState(""),[profile,setProfile]=useState({});
 const timer=useRef(null); useEffect(()=>{const g=sessionStorage.getItem("networkly_ai_goal");if(g){setAutoGoal(g);sessionStorage.removeItem("networkly_ai_goal")}fetch("/api/onboarding").then(r=>r.json()).then(j=>setProfile(j.profile||{})).catch(()=>{});return()=>clearInterval(timer.current)},[]);
 async function generate(e){e.preventDefault();setBusy(true);setMsg("Création lancée...");const r=await fetch("/api/alexya/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,prompt,aspectRatio:ratio,duration})});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||"Erreur");return}setJob(j.job);watch(j.job.id)}
 function watch(id){clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch("/api/alexya/status?id="+encodeURIComponent(id));const j=await r.json();if(r.ok){setJob(j.job);if(["completed","failed"].includes(j.job.status)){clearInterval(timer.current);setMsg(j.job.status==="completed"?"Ton média est prêt ✓":"La génération a échoué.")}}},3000)}
 async function save(go=false){setBusy(true);const r=await fetch("/api/alexya/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.id})});const j=await r.json();setBusy(false);if(r.ok){setSaved(j.item);setMsg("Ajouté à ta bibliothèque ✓");if(go)sessionStorage.setItem("networkly_schedule_caption",caption);location.href="/schedule?media="+encodeURIComponent(j.item.id)}else setMsg(j.error||"Enregistrement impossible")}
 async function completePost(){if(autoGoal.trim().length<3){setMsg("Décris ton objectif.");return}setBusy(true);setMsg("Networkly prépare ta publication...");const r=await fetch("/api/generate-complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal:autoGoal,network:"Instagram / TikTok",tone:profile.tone||"Naturel",profile})});const j=await r.json();if(!r.ok){setBusy(false);setMsg(j.error||"Création impossible");return}setConcept(j.concept);setCaption(j.caption);setPrompt(j.visualPrompt);setKind("image");setRatio("4:5");const gr=await fetch("/api/alexya/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"image",prompt:j.visualPrompt,aspectRatio:"4:5"})});const gj=await gr.json();setBusy(false);if(!gr.ok){setMsg(gj.error||"Le concept est prêt mais le visuel n’a pas pu être lancé.");return}setJob(gj.job);setMsg("Concept et légende prêts. Création du visuel...");watch(gj.job.id)}
 async function generateCaption(){setBusy(true);const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request:"Rédige une légende de réseau social prête à publier pour ce visuel : "+prompt,platform:"Instagram / TikTok",tone:"naturel et engageant"})});const j=await r.json();setBusy(false);setCaption(j.text||j.content||j.result||"");}
 return <div className="calendarpage"><header><div><p className="eyebrow">STUDIO VISUEL IA</p><h1>Crée ton visuel</h1><p>Génère une image ou une vidéo, puis conserve-la dans ta bibliothèque.</p></div><a href="/" className="linkbtn">Retour</a></header>
 <div className="admincard" style={{marginBottom:20}}><p className="eyebrow">PUBLICATION COMPLÈTE</p><h2>Donne simplement ton objectif</h2><p>Networkly prépare le concept, la légende et le visuel.</p><label>Que veux-tu obtenir ?<textarea value={autoGoal} onChange={e=>setAutoGoal(e.target.value)} placeholder="Ex : recruter de nouvelles vendeuses pour mon activité, présenter mon nouveau parfum..."/></label><button className="generate" type="button" disabled={busy} onClick={completePost}><Sparkles size={18}/> Créer toute ma publication</button>{concept&&<div className="result"><b>Concept proposé</b><p>{concept}</p></div>}</div><div className="aistudio"><form className="admincard" onSubmit={generate}><div className="typepicker"><button type="button" className={kind==="image"?"active":""} onClick={()=>{setKind("image");setRatio("1:1")}}><ImageIcon/> Image</button><button type="button" className={kind==="video"?"active":""} onClick={()=>{setKind("video");setRatio("9:16")}}><Video/> Vidéo</button></div>
 <label>Décris ce que tu veux créer<textarea required minLength="3" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex : visuel publicitaire premium, lumière chaude..."/></label>
 <label>Format<select value={ratio} onChange={e=>setRatio(e.target.value)}>{kind==="image"?<><option>1:1</option><option>4:5</option><option>16:9</option><option>9:16</option></>:<><option>9:16</option><option>16:9</option></>}</select></label>
 {kind==="video"&&<label>Durée<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="5">5 secondes</option><option value="10">10 secondes</option></select></label>}
 <button className="generate" disabled={busy}><Sparkles size={18}/> {busy?"Création...":"Générer avec l’IA"}</button>{msg&&<p className="notice">{msg}</p>}</form>
 <div className="admincard airesult"><p className="eyebrow">APERÇU</p>{!job&&<div className="empty">Ton prochain visuel apparaîtra ici.</div>}{job&&job.status!=="completed"&&<div className="generating"><Sparkles/><strong>Génération en cours</strong><span>Networkly prépare ton média.</span></div>}{job?.status==="completed"&&job.output_url&&<>{job.media_kind==="video"?<video src={job.output_url} controls/>:<img src={job.output_url} alt="Création IA"/>}<label>Légende<textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Ajoute une légende ou génère-la avec Networkly..."/></label><button className="linkbtn" type="button" onClick={generateCaption} disabled={busy}>Générer la légende</button>{!saved?<><button className="generate" onClick={()=>save(false)} disabled={busy}><Library size={18}/> Ajouter à ma bibliothèque</button><button className="generate" onClick={()=>save(true)} disabled={busy}><CalendarClock size={18}/> Programmer maintenant</button></>:<button className="generate" onClick={()=>{sessionStorage.setItem("networkly_schedule_caption",caption);location.href="/schedule?media="+encodeURIComponent(saved.id)}}>Programmer ce média</button>}</>}</div></div></div>
}