import {createServerSupabase} from "../../../../lib/supabase/server";
import {requireActiveUser} from "../../../../lib/auth/active-user";
export async function POST(req){
 const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});const user=access.user;
 const b=await req.json();const networks=Array.isArray(networks)?[...new Set(networks.filter(x=>["instagram","facebook","tiktok"].includes(x)))]:[];if(!b.id||!networks.length)return Response.json({error:"Choisis au moins un réseau valide."},{status:400});
 const {data:item}=await s.from("content_items").select("*").eq("id",b.id).eq("user_id",user.id).single();if(!item||item.status!=="draft")return Response.json({error:"Ce contenu n’est pas un brouillon."},{status:409});
 const {data:settings}=await s.from("user_publish_settings").select("publish_mode").eq("user_id",user.id).maybeSingle();const mode=b.publishMode||settings?.publish_mode||"approval";if(mode!=="draft"){const {data:connections}=await s.from("social_connections").select("provider").eq("user_id",user.id).eq("connected",true).in("provider",networks);const connected=new Set((connections||[]).map(x=>x.provider));const missing=networks.filter(x=>!connected.has(x));if(missing.length)return Response.json({error:`Connecte d’abord : ${missing.join(", ")}`},{status:409})}
 const patch={status:"planned",platform:networks.join(", "),target_networks:networks,publish_mode:mode,updated_at:new Date().toISOString()};if(b.date)patch.scheduled_date=b.date;if(b.time)patch.scheduled_time=b.time;const date=b.date||item.scheduled_date,time=b.time||item.scheduled_time;if(date&&time){patch.scheduled_at=new Date(`${date}T${String(time).slice(0,5)}`).toISOString();patch.schedule_timezone=b.timezone||item.schedule_timezone||"Europe/Paris";}
 const {error}=await s.from("content_items").update(patch).eq("id",b.id).eq("user_id",user.id);if(error)return Response.json({error:error.message},{status:400});
 if(mode!=="draft"){const {error:te}=await s.from("publish_targets").insert(networks.map(provider=>({user_id:user.id,content_id:b.id,provider,status:mode==="automatic"?"pending":"pending_approval"})));if(te)return Response.json({error:te.message},{status:400})}
 return Response.json({ok:true});
}