"use client";
import {useEffect,useState} from "react";
export default function Billing(){const [code,setCode]=useState(""),[busy,setBusy]=useState(""),[billing,setBilling]=useState(null);
 useEffect(()=>{fetch("/api/billing/status").then(r=>r.json()).then(j=>setBilling(j.billing||null))},[]);
 async function cancelSubscription(){if(!confirm("Résilier ton abonnement Networkly Pro ? Le renouvellement automatique sera arrêté."))return;setBusy("cancel");try{const r=await fetch("/api/billing/cancel",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Résiliation impossible");setBilling(x=>({...x,plan:"free",subscription_status:"cancelled",payment_failed_at:null,grace_period_ends_at:null}));alert("Ton abonnement est résilié. Aucun nouveau renouvellement ne sera prélevé.")}catch(e){alert(e.message)}finally{setBusy("")}}
 async function go(provider){setBusy(provider);try{const r=await fetch("/api/billing/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider,promoCode:code})});const j=await r.json();if(j.url)location.href=j.url;else alert(j.error||"Paiement indisponible")}finally{setBusy("")}}
 const late=billing?.subscription_status==="past_due";
 const pending=billing?.subscription_status==="payment_pending";
 const expired=billing?.subscription_status==="payment_expired";
 return <div className="authwrap"><div className="authbox"><p className="eyebrow">NETWORKLY PRO</p><h1>{late?"Paiement à régulariser":pending?"Paiement en attente":expired?"Paiement à recommencer":billing?.plan==="pro"?"Ton abonnement Pro":"Passe à Pro"}</h1>{late?<div className="notice"><strong>Ton renouvellement n’a pas pu être prélevé.</strong><p>Ton accès Pro reste actif encore {billing?.days_remaining??7} jour(s). Régularise avant la fin du délai pour éviter le passage en Free.</p></div>:pending?<div className="notice"><strong>Ton paiement est en cours de confirmation.</strong><p>Il n’est pas nécessaire de payer une deuxième fois. Networkly activera Pro automatiquement dès confirmation du prestataire.</p></div>:expired?<div className="notice"><strong>Le précédent paiement n’a pas été finalisé.</strong><p>Tu peux maintenant recommencer le paiement sans risque de créer un doublon.</p></div>:billing?.plan==="pro"?<p>Ton abonnement Networkly Pro est actif.</p>:<p>Débloque toutes les fonctions premium et la génération avancée.</p>}<div className="pricepreview"><span>Formule actuelle</span><strong>{billing?.plan==="pro"?"Networkly Pro":"Networkly Free"}</strong></div>{billing?.last_payment_at&&<small>Dernier paiement : {new Date(billing.last_payment_at).toLocaleDateString("fr-FR")}</small>}<label>Code promo<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="FACULTATIF"/></label>{!pending&&(billing?.plan!=="pro"||late)&&<><button className="generate" disabled={busy} onClick={()=>go("mollie")}>{busy==="mollie"?"Connexion...":late?"Régulariser avec Mollie":"Payer avec Mollie"}</button><button className="paypalbtn" disabled={busy} onClick={()=>go("paypal")}>{busy==="paypal"?"Connexion...":late?"Régulariser avec PayPal":"Payer avec PayPal"}</button></>}{billing?.plan==="pro"&&!late&&<button className="secondary" disabled={busy} onClick={cancelSubscription}>{busy==="cancel"?"Résiliation...":"Résilier mon abonnement"}</button>}<small>Le prix et les réductions sont vérifiés côté serveur avant le paiement.</small></div></div>}