import {createServerSupabase} from "../../../../lib/supabase/server";\nimport {requireActiveUser} from "../../../../lib/auth/active-user";
export async function POST(req){
 try{
  const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});const user=access.user;
  const b=await req.json();const timezone=b.timezone||"Europe/Paris";const scheduledAt=b.scheduledAt||null;const {data:settings}=await s.from("user_publish_settings").select("*").eq("user_id",user.id).maybeSingle();const publishMode=b.publishMode||settings?.publish_mode||"approval";if(!b.mediaId||!b.date||!b.time||!Array.isArray(b.networks)||!b.networks.length)return Response.json({error:"Informations incomplètes"},{status:400});const networks=[...new Set(b.networks.filter(x=>["instagram","facebook","tiktok"].includes(x)))];if(!networks.length)return Response.json({error:"Choisis au moins un réseau valide."},{status:400});if(publishMode!=="draft"){const {data:connections}=await s.from("social_connections").select("provider").eq("user_id",user.id).eq("connected",true).in("provider",networks);const connected=new Set((connections||[]).map(x=>x.provider));const missing=networks.filter(x=>!connected.has(x));if(missing.length)return Response.json({error:`Connecte d’abord : ${missing.join(", ")}`},{status:409})}
  const {data:m,error:me}=await s.from("media_library").select("*").eq("id",b.mediaId).eq("user_id",user.id).single();if(me||!m)return Response.json({error:"Média introuvable"},{status:404});
  const {data,error}=await s.from("content_items").insert({user_id:user.id,scheduled_date:b.date,scheduled_time:b.time,scheduled_at:scheduledAt,schedule_timezone:timezone,content_type:m.media_type.startsWith("video/")?"Vidéo":"Publication",platform:networks.join(", "),target_networks:networks,objective:"Contenu personnel",title:m.title||m.original_name,body:b.caption||"",status:"planned",publish_mode:publishMode,media_path:m.media_path,media_type:m.media_type,is_ai_generated:m.source==="ai",subtitles_enabled:!!b.subtitles,subtitle_style:b.subtitleStyle||"dynamic"}).select().single();
  if(error)throw error;if(publishMode!=="draft")await s.from("publish_targets").insert(networks.map(provider=>({user_id:user.id,content_id:data.id,provider,status:publishMode==="automatic"?"pending":"pending_approval"})));return Response.json({item:data});
 }catch{return Response.json({error:"Impossible de programmer ce média."},{status:500})}
}