import {createServerSupabase} from "../../../../lib/supabase/server";
import {requireActiveUser} from "../../../../lib/auth/active-user";
export async function POST(req){
 try{
  const s=await createServerSupabase();const access=await requireActiveUser(s);if(!access.ok)return Response.json({error:access.error},{status:access.status});const user=access.user;
  const b=await req.json();const timezone=b.timezone||"Europe/Paris";const scheduledAt=b.publishNow?new Date().toISOString():(b.scheduledAt||null);const {data:settings}=await s.from("user_publish_settings").select("*").eq("user_id",user.id).maybeSingle();const publishMode=b.publishNow?"automatic":(b.publishMode||settings?.publish_mode||"approval");if(!b.mediaId||!Array.isArray(b.networks)||!b.networks.length)return Response.json({error:!b.mediaId?"Aucun média sélectionné.":"Choisis au moins un réseau."},{status:400});if(!b.publishNow&&(!b.date||!b.time))return Response.json({error:!b.date&&!b.time?"Choisis une date et une heure pour programmer la publication.":!b.date?"Choisis une date.":"Choisis une heure."},{status:400});const networks=[...new Set(b.networks.filter(x=>["instagram","facebook","tiktok"].includes(x)))];if(!networks.length)return Response.json({error:"Choisis au moins un réseau valide."},{status:400});if(publishMode!=="draft"){const {data:connections}=await s.from("social_connections").select("provider").eq("user_id",user.id).eq("connected",true).in("provider",networks);const connected=new Set((connections||[]).map(x=>x.provider));const missing=networks.filter(x=>!connected.has(x));if(missing.length)return Response.json({error:`Connecte d’abord : ${missing.join(", ")}`},{status:409})}
  const {data:m,error:me}=await s.from("media_library").select("*").eq("id",b.mediaId).eq("user_id",user.id).single();if(me||!m)return Response.json({error:"Média introuvable"},{status:404});if(networks.includes("tiktok")&&!String(m.media_type||"").startsWith("video/"))return Response.json({error:"TikTok accepte actuellement uniquement les vidéos dans Networkly."},{status:409});
  const {data,error}=await s.from("content_items").insert({user_id:user.id,scheduled_date:b.publishNow?new Date().toISOString().slice(0,10):b.date,scheduled_time:b.publishNow?new Date().toTimeString().slice(0,5):b.time,scheduled_at:scheduledAt,schedule_timezone:timezone,content_type:m.media_type.startsWith("video/")?"Vidéo":"Publication",platform:networks.join(", "),target_networks:networks,objective:"Contenu personnel",title:m.title||m.original_name,body:b.caption||"",status:"planned",publish_mode:publishMode,media_path:m.media_path,media_type:m.media_type,is_ai_generated:m.source==="ai",subtitles_enabled:!!b.subtitles,subtitle_style:b.subtitleStyle||"dynamic"}).select().single();
  if(error)throw error;if(publishMode!=="draft")await s.from("publish_targets").insert(networks.map(provider=>({user_id:user.id,content_id:data.id,provider,status:"pending"})));if(b.publishNow){try{const base=new URL(req.url).origin;const rr=await fetch(base+"/api/publish/run",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+(process.env.CRON_SECRET||"")},body:JSON.stringify({contentId:data.id})});const out=await rr.json().catch(()=>({}));if(!rr.ok)return Response.json({item:data,error:out.error||"Le contenu est enregistré mais la publication immédiate a échoué."},{status:502});return Response.json({item:data,published:true,result:out})}catch(e){return Response.json({item:data,error:e.message||"Publication immédiate impossible"},{status:502})}}return Response.json({item:data});
 }catch{return Response.json({error:"Impossible de programmer ce média."},{status:500})}
}