"use client";
import {useEffect,useState} from "react";
const networks=[["instagram","Instagram"],["facebook","Facebook"],["tiktok","TikTok"]];
export default function Social(){
 const [subs,setSubs]=useState(true),[style,setStyle]=useState("dynamic"),[mode,setMode]=useState("approval"),[pages,setPages]=useState([]),[pageId,setPageId]=useState(""),[msg,setMsg]=useState(""),[tt,setTt]=useState({connected:false,privacy:[]}),[privacy,setPrivacy]=useState(""),[comments,setComments]=useState(true),[duet,setDuet]=useState(true),[stitch,setStitch]=useState(true);
 useEffect(()=>{fetch("/api/social/settings").then(r=>r.json()).then(x=>{if(x.settings){setSubs(x.settings.subtitles_enabled);setStyle(x.settings.subtitle_style);setMode(x.settings.publish_mode);setPrivacy(x.settings.tiktok_privacy||"");setComments(!x.settings.tiktok_disable_comment);setDuet(!x.settings.tiktok_disable_duet);setStitch(!x.settings.tiktok_disable_stitch)}});fetch("/api/social/tiktok-options").then(r=>r.json()).then(setTt);fetch("/api/social/meta-pages").then(r=>r.json()).then(x=>setPages(x.pages||[]))},[]);
 function connect(provider){location.href="/api/social/connect/"+provider}
 async function saveSettings(){const r=await fetch("/api/social/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publish_mode:mode,subtitles_enabled:subs,subtitle_style:style,tiktok_privacy:privacy,tiktok_disable_comment:!comments,tiktok_disable_duet:!duet,tiktok_disable_stitch:!stitch})});setMsg(r.ok?"Préférences enregistrées ✓":"Erreur d’enregistrement")}
 async function selectMeta(){const p=pages.find(x=>x.id===pageId);if(!p)return;const r=await fetch("/api/social/meta-select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageId:p.id,igUserId:p.instagram?.id||null})});const j=await r.json();setMsg(r.ok?"Destination Meta enregistrée ✓":j.error||"Erreur")}
 return <div className="calendarpage"><header><div><p className="eyebrow">RÉSEAUX SOCIAUX</p><h1>Connecte tes comptes</h1><p>Autorise Networkly depuis la fenêtre officielle de chaque réseau.</p></div><a href="/" className="linkbtn">Retour</a></header><div className="socialgrid">{networks.map(([id,name])=><div className="admincard" key={id}><h2>{name}</h2><p>Planifie et publie ton contenu depuis Networkly.</p><button className="generate" onClick={()=>connect(id)}>Connecter {name}</button></div>)}</div>{pages.length>0&&<div className="admincard"><p className="eyebrow">META</p><h2>Choisis ta destination</h2><label>Page Facebook<select value={pageId} onChange={e=>setPageId(e.target.value)}><option value="">Sélectionner...</option>{pages.map(p=><option key={p.id} value={p.id}>{p.name}{p.instagram?" + Instagram":""}</option>)}</select></label><button className="generate" onClick={selectMeta} disabled={!pageId}>Enregistrer cette Page</button></div>}{tt.connected&&<div className="admincard"><p className="eyebrow">TIKTOK</p><h2>Préférences de publication</h2><label>Qui peut voir mes vidéos ?<select value={privacy} onChange={e=>setPrivacy(e.target.value)}><option value="">Choisir...</option>{tt.privacy.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="switchrow"><input type="checkbox" checked={comments} onChange={e=>setComments(e.target.checked)}/> Autoriser les commentaires</label><label className="switchrow"><input type="checkbox" checked={duet} onChange={e=>setDuet(e.target.checked)}/> Autoriser les Duos</label><label className="switchrow"><input type="checkbox" checked={stitch} onChange={e=>setStitch(e.target.checked)}/> Autoriser les Collages</label></div>}<div className="admincard"><p className="eyebrow">PUBLICATION</p><h2>Comportement par défaut</h2><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="draft">Brouillon uniquement</option><option value="approval">Demander ma validation</option><option value="automatic">Publication automatique</option></select></label></div><div className="admincard"><p className="eyebrow">VIDÉOS</p><h2>Sous-titres automatiques</h2><label className="switchrow"><input type="checkbox" checked={subs} onChange={e=>setSubs(e.target.checked)}/> Ajouter automatiquement des sous-titres</label>{subs&&<label>Style<select value={style} onChange={e=>setStyle(e.target.value)}><option value="dynamic">Dynamique</option><option value="clean">Épuré</option><option value="premium">Premium</option><option value="karaoke">Mot par mot</option></select></label>}<button className="generate" onClick={saveSettings}>Enregistrer mes préférences</button>{msg&&<p className="notice">{msg}</p>}</div></div>
}