"use client";
import {useEffect,useState} from "react";
import {Sparkles,Plus,Trash2,Library,CalendarClock} from "lucide-react";
function storyPrompt(i,subject=""){const roles=[
"OUVERTURE — crée une accroche visuelle forte qui introduit le sujet et donne envie de voir la suite",
"DÉVELOPPEMENT — montre une idée, un détail, un conseil ou une scène différente qui apporte de la valeur sans répéter la première story",
"CONCLUSION / CTA — termine la séquence avec une scène différente et une invitation claire à réagir, répondre ou passer à l’action"
];const role=roles[i]||`SUITE ${i+1} — fais progresser naturellement l’histoire avec une nouvelle scène, un nouvel angle et sans répéter les cartes précédentes`;return subject?`Story Instagram verticale 9:16. Sujet global : ${subject}. Rôle de cette carte : ${role}. Crée uniquement le visuel de cette carte, cohérent avec la même séquence mais avec une composition et une scène distinctes.`:""}
function newCard(i,subject=""){return {id:Date.now()+i,title:"Story "+(i+1),prompt:storyPrompt(i,subject),job:null,busy:false,msg:"",credits:null}}
export default function Stories(){
 const [cards,setCards]=useState([]),[subject,setSubject]=useState(""),[balance,setBalance]=useState(null);
 useEffect(()=>{const q=new URLSearchParams(location.search),s=q.get("subject")||q.get("goal")||"";setSubject(s);setCards([newCard(0,s),newCard(1,s),newCard(2,s)]);fetch("/api/credits").then(r=>r.json()).then(j=>setBalance(j.balance??j.credits??null)).catch(()=>{})},[]);
 const patch=(id,v)=>setCards(x=>x.map(c=>c.id===id?{...c,...v}:c));
 const add=()=>setCards(x=>[...x,newCard(x.length,subject)]);
 const remove=id=>setCards(x=>x.filter(c=>c.id!==id));
 async function generate(card){
  patch(card.id,{busy:true,msg:"Génération..."});
  const r=await fetch("/api/alexya/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"image",prompt:card.prompt,aspectRatio:"9:16"})});const j=await r.json();
  if(!r.ok){patch(card.id,{busy:false,msg:j.error||"Erreur"});return}
  const cost=j.job?.credits_charged??null;patch(card.id,{job:j.job,credits:cost,msg:"Création en cours..."});
  if(cost!=null)setBalance(v=>v==null?v:Math.max(0,v-cost));
  let tries=0;const timer=setInterval(async()=>{tries++;const sr=await fetch("/api/alexya/status?id="+encodeURIComponent(j.job.id),{cache:"no-store"});const sj=await sr.json();if(sr.ok&&sj.job){patch(card.id,{job:sj.job});if(["completed","failed"].includes(sj.job.status)){clearInterval(timer);patch(card.id,{job:sj.job,busy:false,msg:sj.job.status==="completed"?"Story prête ✓":"Échec de la génération"})}}if(tries>90){clearInterval(timer);patch(card.id,{busy:false,msg:"La génération prend plus de temps que prévu."})}},4000);
 }
 async function save(card,go=false){if(!card.job?.id)return;patch(card.id,{msg:"Enregistrement..."});const r=await fetch("/api/alexya/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:card.job.id})});const j=await r.json();if(!r.ok){patch(card.id,{msg:j.error||"Enregistrement impossible"});return}patch(card.id,{msg:"Ajoutée à la bibliothèque ✓"});if(go)location.href="/schedule?media="+encodeURIComponent(j.item.id)}
 return <div className="calendarpage storiespage"><style>{`.storiespage{max-width:1280px;margin:auto}.storieshero{background:linear-gradient(135deg,#f5faf7,#fff);border:1px solid #dfe8e2;border-radius:28px;padding:28px;margin-bottom:22px}.storygrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.storycard{background:#fff;border:1px solid #e3e7e4;border-radius:24px;overflow:hidden;box-shadow:0 12px 35px rgba(20,45,35,.06)}.storyvisual{background:#f3f6f4;aspect-ratio:9/12;display:flex;align-items:center;justify-content:center;overflow:hidden}.storyvisual img{width:100%;height:100%;object-fit:cover}.storybody{padding:20px}.storyhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.storynumber{font-size:12px;font-weight:800;letter-spacing:.12em;color:#2f6654}.storybody textarea{width:100%;min-height:130px;border:1px solid #dfe4e1;border-radius:16px;padding:14px;resize:vertical}.storygenerate{width:100%;margin-top:12px;border:0;border-radius:14px;background:#111713;color:#fff;padding:14px;font-weight:800}.storymeta{display:flex;justify-content:space-between;align-items:center;margin-top:10px;color:#65736d;font-size:13px}.addstory{margin-top:22px;border:1px dashed #94aa9f;background:#f7faf8;border-radius:18px;padding:16px 22px;font-weight:800}@media(max-width:900px){.storygrid{grid-template-columns:1fr}.storyvisual{aspect-ratio:9/10}}`}</style><header><div><p className="eyebrow">STORIES</p><h1>Crée ta séquence</h1><p>Chaque carte possède son propre générateur. Modifie, génère et enregistre chaque story indépendamment.</p></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span className="linkbtn">Crédits : <b>{balance??"—"}</b></span><a href="/" className="linkbtn">Retour</a></div></header>
 <div className="storieshero"><label><b>Sujet de la séquence</b><textarea value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ex : présenter une nouveauté en 3 stories"/></label></div>
 <div className="storygrid">{cards.map((c,i)=><article className="storycard" key={c.id}><div className="storyvisual">{c.job?.output_url?<img src={c.job.output_url} alt={c.title}/>:<div className="empty">Story {i+1}<br/>9:16</div>}</div><div className="storybody"><div className="storyhead"><div><span className="storynumber">STORY {String(i+1).padStart(2,"0")}</span><br/><strong>{i===0?"Accroche":i===1?"Développement":i===2?"Conclusion / CTA":"Suite"}</strong></div>{cards.length>1&&<button className="iconbtn" onClick={()=>remove(c.id)}><Trash2 size={16}/></button>}</div><textarea value={c.prompt} onChange={e=>patch(c.id,{prompt:e.target.value})} placeholder="Décris uniquement cette story..."/><button className="storygenerate" disabled={c.busy||c.prompt.trim().length<3} onClick={()=>generate(c)}><Sparkles size={16}/>{c.busy?" Génération...":" Générer cette story"}</button><div className="storymeta"><span>Format Instagram · 9:16</span>{c.credits!=null&&<span>-{c.credits} crédits</span>}</div>{c.msg&&<p className="notice">{c.msg}</p>}{c.job?.status==="completed"&&<div className="mediaactions"><button className="linkbtn" onClick={()=>save(c)}><Library size={15}/> Bibliothèque</button><button className="linkbtn" onClick={()=>save(c,true)}><CalendarClock size={15}/> Programmer</button></div>}</div></article>)}</div>
 <button className="addstory" type="button" onClick={add}><Plus size={17}/> Ajouter une story</button>
 </div>
}